- getgauge/impl_loader.py
- getgauge/processor.py
- getgauge/static_loader.py
- getgauge/util.py
- getgauge/validator.py
- start.py
- tests/test_processor.py
- tests/test_static_loader.py
Populating step_registry with statically parsed files getgauge/gauge-vscode#109 #19
compiling implementation only for execution phase.
> Static Parsing

- getgauge/impl_loader.py
- getgauge/registry.py
- getgauge/static_loader.py
- start.py
Changes needed as when gauge is running in debug mode, we need to output print in particular format.
> using logger instead of print. #40

- getgauge/static_loader.py
- start.py
- tests/test_lsp_server.py
- tests/test_processor.py
- tests/test_static_loader.py
GRPC uses only one thread to run.
reloading steps only if valid ast can be generated
> fixes issues in step usages

- getgauge/lsp_server.py
- getgauge/refactor.py
- tests/test_lsp_server.py
- tests/test_refactor.py
This reverts commit 2416d89af5bfb56a11a6a3def6517cfab8370f3f.
> Revert "Revert "sending file diff to gauge.""

- getgauge/refactor.py
- tests/test_lsp_server.py
- tests/test_refactor.py
The PR #76  has to be merged before merging this.
> generating index based parameter names #31

- getgauge/registry.py
- getgauge/static_loader.py
optimising initialisation
Execution time for the sample attached in #54 
Before:
gauge run specs  125.13s user 0.92s system 97% cpu 2:09.64 total
After:
gauge run specs  5.18s user 0.82s system 87% cpu 6.879 total
> #54 Optimisation

- docs/source/installation.rst
- Gauge link has been added for reference
- spell correction done for the word `nightly`
> minor spell correction and gauge link addition for reference

- setup.tmpl
This is the patch for fixing #186 by bumping the version of grpcio in `setup.tmpl`.
> updated grpcio version to fit requirements.txt

- build.py
- getgauge/processor.py
- requirements.txt
- setup.tmpl
- start.py
- since vscode removes support for ptvsd soon
Fixes #180
> Use debugpy instead of ptvsd

- python.json
Signed-off-by: BugDiver <vinaysh@thoughtworks.com>
> Bump version for release.

- python.json
- setup.tmpl
> Update grpcio version in setup tmpl

- .github/workflows/tests.yml
> Replace deprecated 'add-path' usage

- tests/test_python.py
> Remove deprecated datastore factory tests

- python.json
> Bump version

- .github/workflows/release_on_pr.yml
> Remove use of hub action

- .github/workflows/release_on_pr.yml
> Use GITHUB_ENV

- .github/workflows/tests.yml
> Use setup gauge action

- .github/workflows/tests.yml
> Use released version of html report and js plugins

- python.json
- setup.tmpl
fixes getgauge/gauge#2060
﻿Signed-off-by: sriv <srikanth.ddit@gmail.com>
> use latest grpcio, fixes install issue in apple silicon

- .github/dependabot.yml
- .github/workflows/release_on_pr.yml
- .github/workflows/tests.yml
- CONTRIBUTING.md
- python.json
Changes:
- Re-enables dependabot updates
- Fixes an issue duplicate action triggers
> Reenables dependabot updates

- build.py
- check_and_install_getgauge.py
- python.json
> Only do --user installs if we think we are not in a venv/virtualenv
